apiVersion: v1
kind: Service
metadata:
  name: abfallkalender
  namespace: gamma-lightning-talk
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: abfallkalender